In [1]:
# Question 1
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
#Addition of 2
addn=arr+2
print(addn)
# Multiplication by 3
multn= arr*3
print(multn)
#Division by 2
divn = arr/2
print(divn)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [2]:
# Question 2
arr = np.array([1,2,3,6,4,5])
rev=arr[::-1]
print(arr)
print(rev)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [3]:
# Question 2 (i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,counts=np.unique(x,return_counts=True)
most_freq=values[np.argmax(counts)]
ind=np.where(x==most_freq)[0]
print("Most frequent value:", most_freq)
print("Frequency:", np.max(counts))
print("Indices:", ind)

Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]


In [4]:
# Question 2 (ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values,counts=np.unique(y,return_counts=True)
most_freq=values[np.argmax(counts)]
ind=np.where(y==most_freq)[0]
print("Most frequent value:", most_freq)
print("Frequency:", np.max(counts))
print("Indices:", ind)

Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


In [5]:
# Question 3
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [6]:
# Question 4
ucs420_Tanshi=np.linspace(10,100,25)
print("array:",ucs420_Tanshi)
print("Dimensions:", ucs420_Tanshi.ndim)
print("Shape:", ucs420_Tanshi.shape)
print("Total elements:", ucs420_Tanshi.size)
print("Data type:", ucs420_Tanshi.dtype)
print("Total bytes:", ucs420_Tanshi.nbytes)
# Transpose using reshape
transpose_reshape = ucs420_Tanshi.reshape(1, 25).T
print("Transpose using reshape:",transpose_reshape)

# Transpose using T
transpose_T = ucs420_Tanshi.T
print("Using T attribute:",transpose_T)

array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [7]:
# Question 5
import numpy as np

ucs420_Tanshi = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:",ucs420_Tanshi)

print("Mean:", np.mean(ucs420_Tanshi))
print("Median:", np.median(ucs420_Tanshi))
print("Maximum:", np.max(ucs420_Tanshi))
print("Minimum:", np.min(ucs420_Tanshi))
print("Unique elements:", np.unique(ucs420_Tanshi))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_Tanshi = ucs420_Tanshi.reshape(4, 3)
print("Reshaped Array:",reshaped_ucs420_Tanshi)

# Resize to 2 rows and 3 columns
resized_ucs420_Tanshi = np.resize(ucs420_Tanshi, (2, 3))
print("Resized Array:",resized_ucs420_Tanshi)

Original Array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array: [[10 20 30]
 [40 50 60]]
