In [1]:
# Q1
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
corrected = temperature + 2

print("Original temperatures:", temperature)
print("Corrected temperatures:", corrected)
fahrenheit = (9 / 5) * corrected + 32
print("Temperatures in Fahrenheit:", fahrenheit)
greater_than_32 = corrected[corrected > 32]
print("Readings greater than 32°C:", greater_than_32)
count = np.sum(corrected> 32)
print("Number of readings greater than 32°C:", count)


Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


In [2]:
# Q2
steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]])
total_steps=np.sum(steps)
print("Total steps ",total_steps)
average_steps=np.mean(steps)
print("Average steps ",average_steps)
max_steps=np.max(steps)
print("Maximum steps ",max_steps)
min_steps=np.min(steps)
print("Minimum steps ",min_steps)
daily_total = np.sum(steps, axis=0)
print("Total steps for each day:", daily_total)
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

max_index = np.argmax(steps)
print("Index of maximum value:", max_index)
position = np.unravel_index(np.argmax(steps), steps.shape)
print("User/day position:", position)
print("Maximum steps:", steps[position])


Total steps  84200
Average steps  7016.666666666667
Maximum steps  9500
Minimum steps  4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Index of maximum value: 11
User/day position: (np.int64(3), np.int64(2))
Maximum steps: 9500


In [3]:
# Q3
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

# b) Slice
subset = original[1:4]
print("Subset:", subset)

# c) Modify view
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

# d) Copy
copied_array = original[1:4].copy()
copied_array[0] = 500

print("Original:", original)
print("Copied array:", copied_array)

# e) arange and reshape
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

# f) Indexing and slicing
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

# g) flatten and ravel
flattened = matrix.flatten()
raveled = matrix.ravel()

print("Flatten:", flattened)
print("Ravel:", raveled)

# h) Modify ravel
raveled[0] = 1000

print("Ravel:", raveled)
print("Original matrix:")
print(matrix)

# i) Modify flatten
flattened[1] = 500

print("Flatten:", flattened)
print("Original matrix:")
print(matrix)

# j) Array properties
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4]
Original: [  1 999   3   4   5   6]
Subset: [999   3   4]
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Flatten: [  1 500   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [4]:
# Question 4
y = np.array([40, 65, 30, 85])

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

# a)
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

# b)
print("X.T:",X.T)

# c)
print("X.T @ X:",X.T @ X)

# d)
inverse = np.linalg.inv(X.T @ X)
print("Inverse:",inverse)

# e)
beta = inverse @ X.T @ y
print("Coefficients:", beta)

# f)
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

# g)
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape: (4, 3)
Dimensions: 2
X.T: [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X: [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse: [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients: [-0.15921454  0.14083853 10.06302242]
Sleep coefficient: -0.1592145415952828
Activity coefficient: 0.14083852991907175
Stress coefficient: 10.063022422714592
Predicted assistance score: 75.27862544778861
